#!/bin/bash
bot="	farid.py
	arik-1.py
	bapak.py
	erwin.py
	ihang.py
	johan.py
	maylinda.py
	meeh.py
	muhammad.py
	rio.py
	2-gstar.py
	3-hau.py
	4-bayu.py
	5-gadsla.py
	6-gaul.py
	7-andi.py
	8-togel.py
	9-anto.py
	10-nakal.py
	11-klip.py
	12.py
	13-joauhar.py
	14-kalu.py
	"

i=1 
while [ $i -le 10 ]; do
cd $HOME
cd uang
cd doge
	for run in $bot; do
		python $run
	done
echo "$i";
((i++))
done
